/*
 * Copyright (C) 2015 Seoul National University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.snu.tempest.operator.window.timescale;

import edu.snu.tempest.operator.window.timescale.impl.DepOutputAndResult;

/**
 * TimescaleWindowOutput generated by time window operator.
 */
public final class TimescaleWindowOutput<V> {
  /**
   * A timescale for the output.
   */
  public final Timescale timescale;

  /**
   * An output.
   */
  public final DepOutputAndResult<V> output;

  /**
   * Start time of the output.
   */
  public final long startTime;

  /**
   * End time of the output.
   */
  public final long endTime;

  /**
   * Is this output fully processed or not.
   */
  public final boolean fullyProcessed;


  /**
   * TimeWindowOutput.
   * @param ts a timescale
   * @param output an output
   * @param startTime a start time of the output
   * @param endTime an end time of the output
   * @param fullyProcessed is this output fully processed or not
   */
  public TimescaleWindowOutput(final Timescale ts,
                               final DepOutputAndResult<V> output,
                               final long startTime,
                               final long endTime,
                               final boolean fullyProcessed) {
    this.timescale = ts;
    this.output = output;
    this.startTime = startTime;
    this.endTime = endTime;
    this.fullyProcessed = fullyProcessed;
  }
  
  @Override
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("ts: ");
    sb.append(timescale);
    sb.append(", range: [");
    sb.append(startTime);
    sb.append("-");
    sb.append(endTime);
    sb.append("], output:");
    sb.append(output);
    return sb.toString();
  }
}
